#: import threading threading
#: import re re
<Classroom>:
    id: classroom
    name: 'classroom'

    MDBoxLayout:
        orientation: 'vertical'
        pos_hint: {'center_x': .5, 'center_y': .5}
        
        MDTabs:
            background_color: (237/255, 162/255, 22/255, .75)
            on_tab_switch: app.root.get_screen('rectory').setTab(False, *args)

            Add:
                id: add
                name: 'add'

                title: 'Agregar'

                FBoxLayout:
                    spacing: dp(5)
                
                    FLabel:
                        text: '[b][size=20][color=#05396E]Datos del Aula[/color][/size][/b]'
                        
                    FLabel:
                        text: '[size=15][color=#EDA216]Las cuentas de rectoria tienen los permisos para agregas mas cuentas de la misma, además de cuentas para profesores, alumnos y agregar horarios.[/color][/size]'
                        
                    MDGridLayout:
                        cols: 2
                        spacing: dp(3)
                        padding: dp(1), dp(0), dp(1), dp(0)
                        size_hint_y: None
                        size: (self.size[0], 50)

                        FIcon:
                            id: add_left_faculty
                            name: 'add_left_faculty'

                            icon: 'minus'
                            disabled: True
                            field: add_faculty
                            position: 'left'
                            
                        FSearcher:
                            id: add_faculty
                            name: 'add_faculty'

                            hint_text: 'Facultades'
                            action: 'faculties'
                            maxim: 1
                            leng: 50    
                            on_text:
                                if self.text == '':\
                                add_left_faculty.disabled = True
                                else:\
                                add_left_faculty.disabled = False

                    FTextField:
                        id: add_classroom
                        name: 'add_classroom'

                        hint_text: 'Nombre del Aula (Ej. (1): 201, (2): Laboratorio)'
                        active: True
                        leng: 100
                    
                    FTextField:
                        id: add_banches
                        name: 'add_banches'

                        hint_text: 'Bancos Disponibles'
                        input_filter: 'int'
                        active: True
                        leng: 3
                    
                    MDFloatLayout:
                        cols: 1
                        
                        FCancelButton:
                            id: add_cancel
                            name: 'add_cancel'

                            text: 'Limpiar'

                        FActionButton:
                            id: add_save
                            name: 'add_save'
                            text: 'Guardar Empleado'
                            x: add_cancel.x - 5 - self.size[0]
                        
            Update:
                id: upd
                name: 'upd'

                title: 'Actualizar'

                FBoxLayout:
                    spacing: dp(5)
                    
                    FLabel:
                        text: '[b][size=20][color=#05396E]Datos del Aula[/color][/size][/b]'
                        
                    FLabel:
                        text: '[size=15][color=#EDA216]Las cuentas de rectoria tienen los permisos para agregas mas cuentas de la misma, además de cuentas para profesores, alumnos y agregar horarios.[/color][/size]'
                        
                    FFinder:
                        id: upd_finder_classroom
                        name: 'upd_finder_classroom'

                        hint_text: 'Nombre_Aula: Nombre_Facultad'
                        
                    FSearcher:
                        id: upd_faculty
                        name: 'upd_faculty'

                        hint_text: "Facultad"
                        disabled: True
                        leng: 50
                    
                    FSearcher:
                        id: upd_classroom
                        name: 'upd_classroom'

                        hint_text: "Nombre del Aula (Ej. (1): 201, (2): Laboratorio)"
                        disabled: True
                        leng: 80
                    
                    FTextField:
                        id: upd_banches
                        name: 'upd_banches'

                        hint_text: 'Nombre'
                        disabled: True
                        leng: 3
                    
                    MDFloatLayout:
                        cols: 1
                        
                        FCancelButton:
                            id: upd_cancel
                            name: 'upd_cancel'

                            text: 'Limpiar'
                            disabled: True

                        FActionButton:
                            id: upd_save
                            name: 'upd_save'

                            text: 'Guardar Modificaciones'
                            disabled: True
                            x: upd_cancel.x - 5 - self.size[0]
        
            Delete:
                id: del
                name: 'del'

                title: 'Eliminar'

                FBoxLayout:
                    spacing: dp(5)
                    
                    FLabel:
                        text: '[b][size=20][color=#05396E]Datos del Aula[/color][/size][/b]'
                        
                    FLabel:
                        text: '[size=15][color=#EDA216]Las cuentas de rectoria tienen los permisos para agregas mas cuentas de la misma, además de cuentas para profesores, alumnos y agregar horarios.[/color][/size]'
                        
                    FFinder:
                        id: del_enrollment
                        name: 'del_enrollment'

                        hint_text: 'Matricula'
                        
                    FTextField:
                        id: del_middle_name
                        name: 'del_middle_name'

                        hint_text: "Primer Apellido"
                        disabled: True
                        active: True
                        leng: 30
                    
                    FTextField:
                        id: del_last_name
                        name: 'del_last_name'

                        hint_text: 'Segundo Apellido'
                        disabled: True
                        active: True
                        leng: 30
                    
                    FTextField:
                        id: del_name
                        name: 'del_name'

                        hint_text: 'Nombre'
                        disabled: True
                        active: True
                        leng: 50
                    
                    FTextField:
                        id: del_email
                        name: 'del_email'

                        hint_text: 'Correo Universitario'
                        disabled: True
                        active: False
                        leng: 40
                    
                    FTextField:
                        id: del_pass
                        name: 'del_pass'

                        hint_text: 'Contraseña'
                        disabled: True
                        active: False
                        leng: 16

                    MDFloatLayout:
                        cols: 1
                        
                        FCancelButton:
                            id: del_cancel
                            name: 'del_cancel'

                            text: 'Limpiar'
                            disabled: True

                        FActionButton:
                            id: del_save
                            name: 'del_save'

                            text: 'Guardar Modificaciones'
                            disabled: True
                            x: upd_cancel.x - 5 - self.size[0]